const screens=[...document.querySelectorAll(".screen")],music=document.getElementById("music"),sound=document.getElementById("music-toggle");let musicStarted=false;
function startMusic(){if(!music||musicStarted)return;music.volume=.5;music.play().then(()=>{musicStarted=true;sound.textContent="♫";document.body.classList.add("music-on")}).catch(()=>{})}
function go(id){startMusic();screens.forEach(s=>s.classList.toggle("active",s.id===id));window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.go)));
document.addEventListener("pointerdown",startMusic,{once:true});
document.addEventListener("keydown",startMusic,{once:true});
sound.addEventListener("click",e=>{e.stopPropagation();if(music.paused){music.play().then(()=>{musicStarted=true;sound.textContent="♫";document.body.classList.add("music-on")}).catch(()=>{})}else{music.pause();sound.textContent="♪";document.body.classList.remove("music-on")}});
const questions=[
{q:"Which moment feels most like the beginning of your story?",a:["The first time we met","Our first proper conversation","The first trip together","Something completely unexpected"],c:0},
{q:"What has made your journey special?",a:["The adventures","The family","The ordinary days","All of the above ♥"],c:3},
{q:"After all these years, what is the best answer?",a:["Still laughing together","Still making memories","Still choosing each other","Every single one"],c:3}
];let qi=0;const qEl=document.getElementById("question"),ans=document.getElementById("answers"),fb=document.getElementById("feedback"),prog=document.getElementById("progress"),qn=document.getElementById("q-number");
function render(){const q=questions[qi];qEl.textContent=q.q;qn.textContent=String(qi+1).padStart(2,"0");prog.style.width=((qi/questions.length)*100)+"%";fb.textContent="";ans.innerHTML="";q.a.forEach((txt,i)=>{const b=document.createElement("button");b.type="button";b.className="answer";b.textContent=txt;b.addEventListener("click",()=>{[...ans.children].forEach(x=>x.disabled=true);if(i===q.c){b.classList.add("correct");fb.textContent="That sounds like a beautiful answer. ♥"}else{b.classList.add("wrong");fb.textContent="Maybe — but the best answer is whatever makes you both smile."}setTimeout(()=>{qi++;if(qi<questions.length)render();else{prog.style.width="100%";go("memories")}},600)});ans.appendChild(b)})}render();
const video=document.getElementById("surprise-video"),vp=document.getElementById("video-placeholder");
document.getElementById("surprise").addEventListener("click",()=>{go("video");music.pause();sound.textContent="♪";video.load();video.play().then(()=>{vp.style.display="none";video.style.display="block"}).catch(()=>{});burst()});
document.getElementById("video-ready").addEventListener("click",()=>{video.load();video.style.display="block";vp.style.display="none";video.play().catch(()=>{})});
function burst(){const box=document.getElementById("confetti");for(let i=0;i<85;i++){const p=document.createElement("i");p.className="piece";p.style.left=Math.random()*100+"%";p.style.background=["#d9b773","#b86b78","#f7efe6","#8c7183"][i%4];p.style.setProperty("--x",(Math.random()*240-120)+"px");p.style.animationDelay=Math.random()*.45+"s";box.appendChild(p);setTimeout(()=>p.remove(),3000)}}